### ISSUE TITLE
有个关于 HTTP混淆伪装 的问题希望作者帮我解惑。

### ISSUE THREAD

**Issue by ghost** [mohanson/daze#11]
常规的 HTTP 网站访问流量都是明文的，但是无论是 DAZE 还是 Goflyway SSR 等代理软件混淆伪装的 HTTP 网站访问流量内容都是加密的（毕竟要加密传输），这样的话，会不会显得很假？

明明是 HTTP 网站访问流量，却每次都是加密传输，这要是 HTTPS 的话还好说，HTTP 的总感觉不对劲。。。

作者你帮我解释下，是不是哪里我没想到。。

**Comment by mohanson** [comment]
daze 混淆采用的是 HTTP Header 明文, 而 HTTP Body 加密传输. 这是符合 HTTP 规则的, 因为类似图片, 视频等内容它们均是人类不可读的二进制串, gfw 无法知道不可读的 HTTP Body 里面到底传输的是什么类型的资源.

**Comment by ghost** [comment]
谢谢解答~
