### ISSUE TITLE
Does daze support ipv6 address?

### ISSUE THREAD

**Issue by Whtie4622** [mohanson/daze#20]

**Comment by mohanson** [comment]
For filter "auto" (-f auto), yes.
For filter "ipcn" (-f ipcn), no. See: https://github.com/mohanson/daze/blob/master/daze.go#L234

It's easy to add ipv6 support, but APNIC(http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest) did not give a list of ipv6 assigned to China PR now. We may have to wait another year or two.

Use "-f auto" please if you want to visit the ipv6 website.

**Comment by mohanson** [comment]
I have added ipv6 support just now, please recompile daze.

**Comment by mohanson** [comment]
It's a bit strange, I think there is no difference between ipv6 server and ipv4.
try use "daze server [::]:51958" and "daze client -s your-ipv6-address:51958"

**Comment by Whtie4622** [comment]
Thanks that works!
The difference is that network traffic via ipv6 is free of charge for me 😝
