### ISSUE TITLE
套CDN

### ISSUE THREAD

**Issue by Alvin9999** [mohanson/daze#36]
请问可以套CDN吗？

**Comment by mohanson** [comment]
不可以. Daze 默认的 ashe 协议是 TCP 协议, 另一种带混淆的 asheshadow 协议是 Content-Length 始终为 0 的非常规 HTTP 协议, 它同样会欺骗过 CDN.

但是保留了此扩展能力, 实现预定义的接口即可编写自定义的协议. 相关代码在 ./protocal/... 中.

**Comment by Alvin9999** [comment]
谢谢，最近流量一大了后就会被封端口或者ip，请问有一些建议吗

**Comment by mohanson** [comment]
试用下 `-e asheshadow -m ANY_WEBSITE_LIKE_BAIDU_COM -k YOUR_RANDOM_PASSWORD`.

**Comment by Alvin9999** [comment]
thx
