### ISSUE TITLE
socket5代理无法访问

### ISSUE THREAD

**Issue by vbcc2001** [mohanson/daze#4]
我按照教程进行配置后，运行了服务端。想通过Firefox 浏览器配置socket5代理访问http://www.google.com，显示如下错误：

root@hk-menss:~/go/bin# /root/go/bin/daze server
2018/07/28 00:19:07 Server cipher is daze
2018/07/28 00:19:07 Domain server is 8.8.8.8:53
2018/07/28 00:19:07 Listen and serve on 0.0.0.0:51958
2018/07/28 00:19:16 read tcp 172.31.39.158:51958->183.13.204.134:29977: use of closed network connection
2018/07/28 00:19:16 read tcp 172.31.39.158:51958->183.13.204.134:29974: use of closed network connection
2018/07/28 00:19:24 read tcp 172.31.39.158:51958->183.13.204.134:29992: use of closed network connection
2018/07/28 00:19:24 read tcp 172.31.39.158:51958->183.13.204.134:29994: use of closed network connection
2018/07/28 00:19:25 read tcp 172.31.39.158:51958->183.13.204.134:29995: use of closed network connection
2018/07/28 00:19:25 read tcp 172.31.39.158:51958->183.13.204.134:29996: use of closed network connection
2018/07/28 00:19:30 unexpected EOF

**Comment by mohanson** [comment]
可以粘贴一下客户端日志吗?
